# .goreleaser.yml
project_name: stonkbot

before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - config.toml.example
nfpms:
  - package_name: stonksbot
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    maintainer: Stonkbot <stonki@stonk.tk>
    description: React with emojis on Mattermost posts
    license: WTFPL
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      # Simple config file
      - src: config.toml.example
        dst: /etc/stonks/config.toml.example
        type: config
      - src: stonkbot.service
        dst: /usr/lib/systemd/user/stonkbot.service
        type: config


checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
